# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import luna_service_pb2 as luna__service__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in luna_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LunaAIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_unary(
                '/luna.LunaAI/Chat',
                request_serializer=luna__service__pb2.ChatRequest.SerializeToString,
                response_deserializer=luna__service__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GenerateItinerary = channel.unary_unary(
                '/luna.LunaAI/GenerateItinerary',
                request_serializer=luna__service__pb2.ItineraryRequest.SerializeToString,
                response_deserializer=luna__service__pb2.ItineraryResponse.FromString,
                _registered_method=True)
        self.ReRouteItinerary = channel.unary_unary(
                '/luna.LunaAI/ReRouteItinerary',
                request_serializer=luna__service__pb2.ReRouteRequest.SerializeToString,
                response_deserializer=luna__service__pb2.ItineraryResponse.FromString,
                _registered_method=True)
        self.SwapLocation = channel.unary_unary(
                '/luna.LunaAI/SwapLocation',
                request_serializer=luna__service__pb2.SwapRequest.SerializeToString,
                response_deserializer=luna__service__pb2.SwapResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/luna.LunaAI/HealthCheck',
                request_serializer=luna__service__pb2.Empty.SerializeToString,
                response_deserializer=luna__service__pb2.HealthStatus.FromString,
                _registered_method=True)
        self.SearchTrend = channel.unary_unary(
                '/luna.LunaAI/SearchTrend',
                request_serializer=luna__service__pb2.TrendRequest.SerializeToString,
                response_deserializer=luna__service__pb2.TrendResponse.FromString,
                _registered_method=True)


class LunaAIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateItinerary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReRouteItinerary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwapLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchTrend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LunaAIServicer_to_server(servicer, server):
    from grpc import unary_unary_rpc_method_handler as _unary_unary

    rpc_method_handlers = {
        'Chat': _unary_unary(
            servicer.Chat,
            request_deserializer=luna__service__pb2.ChatRequest.FromString,
            response_serializer=luna__service__pb2.ChatResponse.SerializeToString,
        ),
        'GenerateItinerary': _unary_unary(
            servicer.GenerateItinerary,
            request_deserializer=luna__service__pb2.ItineraryRequest.FromString,
            response_serializer=luna__service__pb2.ItineraryResponse.SerializeToString,
        ),
        'ReRouteItinerary': _unary_unary(
            servicer.ReRouteItinerary,
            request_deserializer=luna__service__pb2.ReRouteRequest.FromString,
            response_serializer=luna__service__pb2.ItineraryResponse.SerializeToString,
        ),
        'SwapLocation': _unary_unary(
            servicer.SwapLocation,
            request_deserializer=luna__service__pb2.SwapRequest.FromString,
            response_serializer=luna__service__pb2.SwapResponse.SerializeToString,
        ),
        'HealthCheck': _unary_unary(
            servicer.HealthCheck,
            request_deserializer=luna__service__pb2.Empty.FromString,
            response_serializer=luna__service__pb2.HealthStatus.SerializeToString,
        ),
        'SearchTrend': _unary_unary(
            servicer.SearchTrend,
            request_deserializer=luna__service__pb2.TrendRequest.FromString,
            response_serializer=luna__service__pb2.TrendResponse.SerializeToString,
        ),
    }

    class _LunaAIHandler(grpc.GenericRpcHandler):
        def service_name(self):
            return 'luna.LunaAI'

        def service(self, handler_call_details):
            # handler_call_details.method is '/luna.LunaAI/Chat' — extract last segment
            method = handler_call_details.method.split('/')[-1]
            return rpc_method_handlers.get(method)

    server.add_generic_rpc_handlers((_LunaAIHandler(),))

    # Register with new API when available (grpcio >= 1.59)
    if hasattr(server, 'add_registered_method_handlers'):
        server.add_registered_method_handlers('luna.LunaAI', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LunaAI(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/luna.LunaAI/Chat',
            luna__service__pb2.ChatRequest.SerializeToString,
            luna__service__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateItinerary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/luna.LunaAI/GenerateItinerary',
            luna__service__pb2.ItineraryRequest.SerializeToString,
            luna__service__pb2.ItineraryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReRouteItinerary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/luna.LunaAI/ReRouteItinerary',
            luna__service__pb2.ReRouteRequest.SerializeToString,
            luna__service__pb2.ItineraryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwapLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/luna.LunaAI/SwapLocation',
            luna__service__pb2.SwapRequest.SerializeToString,
            luna__service__pb2.SwapResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/luna.LunaAI/HealthCheck',
            luna__service__pb2.Empty.SerializeToString,
            luna__service__pb2.HealthStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchTrend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/luna.LunaAI/SearchTrend',
            luna__service__pb2.TrendRequest.SerializeToString,
            luna__service__pb2.TrendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
